server:
  port: 9026
spring:
  application:
    name: eureka-test
  cloud:
    server-token:
      eureka-pro: eureka-pro
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka