server:
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: true
  compression:
    enabled: true
  port: 9016

spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password: wpx1997
    database: 2
    timeout: 20000ms
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 3
        # 最大空闲连接数 默认8
        max-idle: 3
        # 最小空闲连接数 默认0
        min-idle: 0

  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: true

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
      location: ${user.dir}/tmp
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 10000
ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

wpx:
  config:
    salt: ufg48UH849Yhngf4
  server:
    base:
      api-token: main-web-base-api-token
      rest-token: main-web-base-rest-token
      server-token:
        gateway-web: gateway-web-rest-token
        main-cms-base: main-cms-base-rest-token
swagger:
  show: true