server:
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: true
  compression:
    enabled: true
  port: 9021

spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password: wpx1997
    database: 2
    timeout: 20000ms
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 3
        # 最大空闲连接数 默认8
        max-idle: 3
        # 最小空闲连接数 默认0
        min-idle: 0

  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: true

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
      location: ${user.dir}/tmp
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 10000
  okhttp:
    enabled: true
  httpclient:
    enabled: false
application:
  server:
    token:
      api: scheduler-api-token
      rest: scheduler-rest-token
  dubbo:
    version: 1.0.0

swagger:
  enable: true
  application-name: ${spring.application.name}
  group: cms
  description: 接口信息
  version: v1.0.0
  security-scheme:
    Authorization: Authorization
    route_api_token: route_api_token
    route_rest_token: route_rest_token
    User-Id: User-Id
  securityContext: Authorization,route_api_token,route_rest_token,User-Id