[
{
  "method": "POST",
  "url": "/api/base/system/manager",
  "role": [
    "0",
    "1"
  ],
  "description": "添加管理员"
},
{
  "method": "PUT",
  "url": "/api/base/system/manager",
  "role": [
    "0",
    "1"
  ],
  "description": "修改管理员"
},
{
  "method": "DELETE",
  "url": "/api/base/system/manager",
  "role": [
    "0",
    "1"
  ],
  "description": "删除管理员"
},
{
  "method": "GET",
  "url": "/api/base/system/manager/page",
  "role": [
    "0",
    "1"
  ],
  "description": "分页获取管理员信息"
},
{
  "method": "PUT",
  "url": "/api/base/system/manager/password",
  "role": [
    "0",
    "1"
  ],
  "description": "重置管理员密码"
},
{
  "method": "PUT",
  "url": "/api/base/system/manager/state",
  "role": [
    "0"
  ],
  "description": "修改管理员状态"
},
{
  "method": "PUT",
  "url": "/api/base/system/manager/role",
  "role": [
    "0",
    "1"
  ],
  "description": "修改管理员权限"
}
]