server:
  port: 9001
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password: wpx1997
    database: 1
    timeout: 20000ms
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 3
        # 最大空闲连接数 默认8
        max-idle: 3
        # 最小空闲连接数 默认0
        min-idle: 0

module:
  shiro:
    rule: gateway-cms
    token-prefix: ${server.port}
  gateway:
    group: CMS_GROUP
    route-data-id: cms-route
    white-route-data-id: cms-white-route
    route-rouse-data-id: cms-route-rouse
    route-api-token-data-id: cms-route-api-token
swagger:
  group: cms