package com.wpx.exception;

/**
 * @Author: 不会飞的小鹏
 * @Description: 基础模块错误码
 */
public class BaseErrorCodes {

    public static final String NOT_ROOT_EDIT_OTHER_INFO_CODE = "NOT_ROOT_EDIT_OTHER_INFO";
    public static final String NOT_ROOT_CHECK_OTHER_INFO_CODE = "NOT_ROOT_CHECK_OTHER_INFO";
    public static final String ALLOW_ADD_WPX_EXCEPT_ROOT_CODE = "NOT_ALLOW_ADD_WPX_EXCEPT_ROOT";
    public static final String MANAGER_NOT_EXIST_CODE = "MANAGER_NOT_EXIST";
    public static final String MANAGER_UPDATE_EXCEPTION_CODE = "MANAGER_UPDATE_EXCEPTION";
    public static final String MANAGER_DELETE_EXCEPTION_CODE = "MANAGER_DELETE_EXCEPTION";
    public static final String MANAGER_SAVE_EXCEPTION_CODE = "MANAGER_SAVE_EXCEPTION";
    public static final String ROOT_DELETE_EXCEPTION_CODE = "ROOT_CANNOT_DELETE";
    public static final String NOT_ROOT_CANNOT_DELETE_CODE = "NOT_ROOT_CANNOT_DELETE";
    public static final String ROOT_CANNOT_DISABLED_CODE = "ROOT_CANNOT_DISABLED";
    public static final String NOT_ROOT_CANNOT_DISABLED_CODE = "NOT_ROOT_CANNOT_DISABLED";
    public static final String NOT_ALLOW_SUPERIOR_ROLE_CODE = "NOT_ALLOW_SUPERIOR_ROLE";
    public static final String APPLICATION_NOT_EXIST_EXCEPTION_CODE = "APPLICATION_NOT_EXIST";
    public static final String APPLICATION_UPDATE_EXCEPTION_CODE = "APPLICATION_UPDATE_EXCEPTION";
    public static final String APPLICATION_DELETE_EXCEPTION_CODE = "APPLICATION_DELETE_EXCEPTION";
    public static final String APPLICATION_SAVE_EXCEPTION_CODE = "APPLICATION_SAVE_EXCEPTION";
    public static final String APPLICATIONINFO_NOT_EXIST_EXCEPTION_CODE = "APPLICATIONINFO_NOT_EXIST";
    public static final String APPLICATIONINFO_SAVE_EXCEPTION_CODE = "APPLICATIONINFO_SAVE_EXCEPTION";
    public static final String APPLICATIONINFO_UPDATE_EXCEPTION_CODE = "APPLICATIONINFO_UPDATE_EXCEPTION";
    public static final String APPLICATIONINFO_DELETE_EXCEPTION_CODE = "APPLICATIONINFO_DELETE_EXCEPTION";
    public static final String APPLICATIONTOPIC_NOT_EXIST_EXCEPTION_CODE = "APPLICATIONTOPIC_NOT_EXIST";
    public static final String APPLICATIONTOPIC_SAVE_EXCEPTION_CODE = "APPLICATIONTOPIC_SAVE_EXCEPTION";
    public static final String APPLICATIONTOPIC_UPDATE_EXCEPTION_CODE = "APPLICATIONTOPIC_UPDATE_EXCEPTION";
    public static final String APPLICATIONTOPIC_DELETE_EXCEPTION_CODE = "APPLICATIONTOPIC_DELETE_EXCEPTION";
    public static final String USER_NOT_EXIST_EXCEPTION_CODE = "USER_NOT_EXIST";
    public static final String USER_SAVE_EXCEPTION_CODE = "USER_SAVE_EXCEPTION";
    public static final String USER_UPDATE_EXCEPTION_CODE = "USER_UPDATE_EXCEPTION";
    public static final String USER_DELETE_EXCEPTION_CODE = "USER_DELETE_EXCEPTION";

}
